server:
  port: 8082
cloud:
  aws:
    region:
      auto: false
      static: eu-central-1
    stack:
      auto: false
    queue:
      name: bookInfoQueue
      timeout: 10000
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error