package com.jaxel.aws.sqsreceiver.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Book")
public class Book {
  @NotNull
  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String id;
  @NotBlank
  @DynamoDBAttribute
  private String title;
  @NotBlank
  @DynamoDBAttribute
  private String author;
}
